<?php
/**
 * ConsentsApi
 * PHP version 5
 *
 * @category Class
 * @package  Yapily
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yapily API
 *
 * To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)
 *
 * OpenAPI spec version: 0.0.161
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yapily\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Yapily\ApiException;
use Yapily\Configuration;
use Yapily\HeaderSelector;
use Yapily\ObjectSerializer;

/**
 * ConsentsApi Class Doc Comment
 *
 * @category Class
 * @package  Yapily
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConsentsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation addConsentUsingPOST
     *
     * Post consent
     *
     * @param  string $user_uuid userUuid (required)
     * @param  \Yapily\Model\CreateConsentAccessToken $create_consent_access_token createConsentAccessToken (required)
     *
     * @throws \Yapily\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Yapily\Model\Consent
     */
    public function addConsentUsingPOST($user_uuid, $create_consent_access_token)
    {
        list($response) = $this->addConsentUsingPOSTWithHttpInfo($user_uuid, $create_consent_access_token);
        return $response;
    }

    /**
     * Operation addConsentUsingPOSTWithHttpInfo
     *
     * Post consent
     *
     * @param  string $user_uuid userUuid (required)
     * @param  \Yapily\Model\CreateConsentAccessToken $create_consent_access_token createConsentAccessToken (required)
     *
     * @throws \Yapily\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Yapily\Model\Consent, HTTP status code, HTTP response headers (array of strings)
     */
    public function addConsentUsingPOSTWithHttpInfo($user_uuid, $create_consent_access_token)
    {
        $returnType = '\Yapily\Model\Consent';
        $request = $this->addConsentUsingPOSTRequest($user_uuid, $create_consent_access_token);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Yapily\Model\Consent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation addConsentUsingPOSTAsync
     *
     * Post consent
     *
     * @param  string $user_uuid userUuid (required)
     * @param  \Yapily\Model\CreateConsentAccessToken $create_consent_access_token createConsentAccessToken (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addConsentUsingPOSTAsync($user_uuid, $create_consent_access_token)
    {
        return $this->addConsentUsingPOSTAsyncWithHttpInfo($user_uuid, $create_consent_access_token)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation addConsentUsingPOSTAsyncWithHttpInfo
     *
     * Post consent
     *
     * @param  string $user_uuid userUuid (required)
     * @param  \Yapily\Model\CreateConsentAccessToken $create_consent_access_token createConsentAccessToken (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addConsentUsingPOSTAsyncWithHttpInfo($user_uuid, $create_consent_access_token)
    {
        $returnType = '\Yapily\Model\Consent';
        $request = $this->addConsentUsingPOSTRequest($user_uuid, $create_consent_access_token);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'addConsentUsingPOST'
     *
     * @param  string $user_uuid userUuid (required)
     * @param  \Yapily\Model\CreateConsentAccessToken $create_consent_access_token createConsentAccessToken (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function addConsentUsingPOSTRequest($user_uuid, $create_consent_access_token)
    {
        // verify the required parameter 'user_uuid' is set
        if ($user_uuid === null || (is_array($user_uuid) && count($user_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $user_uuid when calling addConsentUsingPOST'
            );
        }
        // verify the required parameter 'create_consent_access_token' is set
        if ($create_consent_access_token === null || (is_array($create_consent_access_token) && count($create_consent_access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_consent_access_token when calling addConsentUsingPOST'
            );
        }

        $resourcePath = '/users/{userUuid}/consents';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($user_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'userUuid' . '}',
                ObjectSerializer::toPathValue($user_uuid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($create_consent_access_token)) {
            $_tempBody = $create_consent_access_token;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json;charset=UTF-8']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json;charset=UTF-8'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createConsentWithCodeUsingPOST
     *
     * Post auth-code and auth-state
     *
     * @param  \Yapily\Model\ConsentAuthCodeRequest $consent_by_auth_code consentByAuthCode (required)
     *
     * @throws \Yapily\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Yapily\Model\Consent
     */
    public function createConsentWithCodeUsingPOST($consent_by_auth_code)
    {
        list($response) = $this->createConsentWithCodeUsingPOSTWithHttpInfo($consent_by_auth_code);
        return $response;
    }

    /**
     * Operation createConsentWithCodeUsingPOSTWithHttpInfo
     *
     * Post auth-code and auth-state
     *
     * @param  \Yapily\Model\ConsentAuthCodeRequest $consent_by_auth_code consentByAuthCode (required)
     *
     * @throws \Yapily\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Yapily\Model\Consent, HTTP status code, HTTP response headers (array of strings)
     */
    public function createConsentWithCodeUsingPOSTWithHttpInfo($consent_by_auth_code)
    {
        $returnType = '\Yapily\Model\Consent';
        $request = $this->createConsentWithCodeUsingPOSTRequest($consent_by_auth_code);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Yapily\Model\Consent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createConsentWithCodeUsingPOSTAsync
     *
     * Post auth-code and auth-state
     *
     * @param  \Yapily\Model\ConsentAuthCodeRequest $consent_by_auth_code consentByAuthCode (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createConsentWithCodeUsingPOSTAsync($consent_by_auth_code)
    {
        return $this->createConsentWithCodeUsingPOSTAsyncWithHttpInfo($consent_by_auth_code)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createConsentWithCodeUsingPOSTAsyncWithHttpInfo
     *
     * Post auth-code and auth-state
     *
     * @param  \Yapily\Model\ConsentAuthCodeRequest $consent_by_auth_code consentByAuthCode (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createConsentWithCodeUsingPOSTAsyncWithHttpInfo($consent_by_auth_code)
    {
        $returnType = '\Yapily\Model\Consent';
        $request = $this->createConsentWithCodeUsingPOSTRequest($consent_by_auth_code);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createConsentWithCodeUsingPOST'
     *
     * @param  \Yapily\Model\ConsentAuthCodeRequest $consent_by_auth_code consentByAuthCode (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createConsentWithCodeUsingPOSTRequest($consent_by_auth_code)
    {
        // verify the required parameter 'consent_by_auth_code' is set
        if ($consent_by_auth_code === null || (is_array($consent_by_auth_code) && count($consent_by_auth_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $consent_by_auth_code when calling createConsentWithCodeUsingPOST'
            );
        }

        $resourcePath = '/consent-auth-code';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($consent_by_auth_code)) {
            $_tempBody = $consent_by_auth_code;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json;charset=UTF-8']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json;charset=UTF-8'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteUsingDELETE
     *
     * Delete consent
     *
     * @param  string $consent_id consentId (required)
     * @param  bool $force_delete forceDelete (optional)
     *
     * @throws \Yapily\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Yapily\Model\ApiResponseOfConsentDeleteResponse
     */
    public function deleteUsingDELETE($consent_id, $force_delete = null)
    {
        list($response) = $this->deleteUsingDELETEWithHttpInfo($consent_id, $force_delete);
        return $response;
    }

    /**
     * Operation deleteUsingDELETEWithHttpInfo
     *
     * Delete consent
     *
     * @param  string $consent_id consentId (required)
     * @param  bool $force_delete forceDelete (optional)
     *
     * @throws \Yapily\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Yapily\Model\ApiResponseOfConsentDeleteResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteUsingDELETEWithHttpInfo($consent_id, $force_delete = null)
    {
        $returnType = '\Yapily\Model\ApiResponseOfConsentDeleteResponse';
        $request = $this->deleteUsingDELETERequest($consent_id, $force_delete);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Yapily\Model\ApiResponseOfConsentDeleteResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteUsingDELETEAsync
     *
     * Delete consent
     *
     * @param  string $consent_id consentId (required)
     * @param  bool $force_delete forceDelete (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteUsingDELETEAsync($consent_id, $force_delete = null)
    {
        return $this->deleteUsingDELETEAsyncWithHttpInfo($consent_id, $force_delete)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteUsingDELETEAsyncWithHttpInfo
     *
     * Delete consent
     *
     * @param  string $consent_id consentId (required)
     * @param  bool $force_delete forceDelete (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteUsingDELETEAsyncWithHttpInfo($consent_id, $force_delete = null)
    {
        $returnType = '\Yapily\Model\ApiResponseOfConsentDeleteResponse';
        $request = $this->deleteUsingDELETERequest($consent_id, $force_delete);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteUsingDELETE'
     *
     * @param  string $consent_id consentId (required)
     * @param  bool $force_delete forceDelete (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deleteUsingDELETERequest($consent_id, $force_delete = null)
    {
        // verify the required parameter 'consent_id' is set
        if ($consent_id === null || (is_array($consent_id) && count($consent_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $consent_id when calling deleteUsingDELETE'
            );
        }

        $resourcePath = '/consents/{consentId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($force_delete !== null) {
            $queryParams['forceDelete'] = ObjectSerializer::toQueryValue($force_delete);
        }

        // path params
        if ($consent_id !== null) {
            $resourcePath = str_replace(
                '{' . 'consentId' . '}',
                ObjectSerializer::toPathValue($consent_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json;charset=UTF-8']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json;charset=UTF-8'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getConsentByIdUsingGET
     *
     * Get consent
     *
     * @param  string $consent_id consentId (required)
     *
     * @throws \Yapily\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Yapily\Model\ApiResponseOfConsent
     */
    public function getConsentByIdUsingGET($consent_id)
    {
        list($response) = $this->getConsentByIdUsingGETWithHttpInfo($consent_id);
        return $response;
    }

    /**
     * Operation getConsentByIdUsingGETWithHttpInfo
     *
     * Get consent
     *
     * @param  string $consent_id consentId (required)
     *
     * @throws \Yapily\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Yapily\Model\ApiResponseOfConsent, HTTP status code, HTTP response headers (array of strings)
     */
    public function getConsentByIdUsingGETWithHttpInfo($consent_id)
    {
        $returnType = '\Yapily\Model\ApiResponseOfConsent';
        $request = $this->getConsentByIdUsingGETRequest($consent_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Yapily\Model\ApiResponseOfConsent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getConsentByIdUsingGETAsync
     *
     * Get consent
     *
     * @param  string $consent_id consentId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConsentByIdUsingGETAsync($consent_id)
    {
        return $this->getConsentByIdUsingGETAsyncWithHttpInfo($consent_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getConsentByIdUsingGETAsyncWithHttpInfo
     *
     * Get consent
     *
     * @param  string $consent_id consentId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConsentByIdUsingGETAsyncWithHttpInfo($consent_id)
    {
        $returnType = '\Yapily\Model\ApiResponseOfConsent';
        $request = $this->getConsentByIdUsingGETRequest($consent_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getConsentByIdUsingGET'
     *
     * @param  string $consent_id consentId (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getConsentByIdUsingGETRequest($consent_id)
    {
        // verify the required parameter 'consent_id' is set
        if ($consent_id === null || (is_array($consent_id) && count($consent_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $consent_id when calling getConsentByIdUsingGET'
            );
        }

        $resourcePath = '/consents/{consentId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($consent_id !== null) {
            $resourcePath = str_replace(
                '{' . 'consentId' . '}',
                ObjectSerializer::toPathValue($consent_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json;charset=UTF-8']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json;charset=UTF-8'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getConsentBySingleAccessConsentUsingPOST
     *
     * Post one time token
     *
     * @param  \Yapily\Model\OneTimeTokenRequest $one_time_token oneTimeToken (required)
     *
     * @throws \Yapily\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Yapily\Model\Consent
     */
    public function getConsentBySingleAccessConsentUsingPOST($one_time_token)
    {
        list($response) = $this->getConsentBySingleAccessConsentUsingPOSTWithHttpInfo($one_time_token);
        return $response;
    }

    /**
     * Operation getConsentBySingleAccessConsentUsingPOSTWithHttpInfo
     *
     * Post one time token
     *
     * @param  \Yapily\Model\OneTimeTokenRequest $one_time_token oneTimeToken (required)
     *
     * @throws \Yapily\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Yapily\Model\Consent, HTTP status code, HTTP response headers (array of strings)
     */
    public function getConsentBySingleAccessConsentUsingPOSTWithHttpInfo($one_time_token)
    {
        $returnType = '\Yapily\Model\Consent';
        $request = $this->getConsentBySingleAccessConsentUsingPOSTRequest($one_time_token);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Yapily\Model\Consent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getConsentBySingleAccessConsentUsingPOSTAsync
     *
     * Post one time token
     *
     * @param  \Yapily\Model\OneTimeTokenRequest $one_time_token oneTimeToken (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConsentBySingleAccessConsentUsingPOSTAsync($one_time_token)
    {
        return $this->getConsentBySingleAccessConsentUsingPOSTAsyncWithHttpInfo($one_time_token)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getConsentBySingleAccessConsentUsingPOSTAsyncWithHttpInfo
     *
     * Post one time token
     *
     * @param  \Yapily\Model\OneTimeTokenRequest $one_time_token oneTimeToken (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConsentBySingleAccessConsentUsingPOSTAsyncWithHttpInfo($one_time_token)
    {
        $returnType = '\Yapily\Model\Consent';
        $request = $this->getConsentBySingleAccessConsentUsingPOSTRequest($one_time_token);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getConsentBySingleAccessConsentUsingPOST'
     *
     * @param  \Yapily\Model\OneTimeTokenRequest $one_time_token oneTimeToken (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getConsentBySingleAccessConsentUsingPOSTRequest($one_time_token)
    {
        // verify the required parameter 'one_time_token' is set
        if ($one_time_token === null || (is_array($one_time_token) && count($one_time_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $one_time_token when calling getConsentBySingleAccessConsentUsingPOST'
            );
        }

        $resourcePath = '/consent-one-time-token';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($one_time_token)) {
            $_tempBody = $one_time_token;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json;charset=UTF-8']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json;charset=UTF-8'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getConsentsUsingGET
     *
     * Get consents sorted by creation date
     *
     * @param  string[] $filter_application_user_id Filter consents by your application user Id (applicationUserId) (optional)
     * @param  string[] $filter_user_uuid Filter consents by Yapily user Id (userUuid) (optional)
     * @param  string[] $filter_institution Use this parameter to filter consent by institution, using the Yapily institution Id (optional)
     * @param  string[] $filter_status Use this parameter to filter consent by status (optional)
     * @param  string $from Use this parameter to filter consents created after the date specified (optional)
     * @param  string $before Use this parameter to filter consents created before the date specified (optional)
     * @param  int $limit Use this parameter to limit consent results, max limit is 20 (optional)
     * @param  int $offset Use this parameter to specify the offset of the results (optional, default to 0)
     *
     * @throws \Yapily\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Yapily\Model\ApiListResponseOfConsent
     */
    public function getConsentsUsingGET($filter_application_user_id = null, $filter_user_uuid = null, $filter_institution = null, $filter_status = null, $from = null, $before = null, $limit = null, $offset = '0')
    {
        list($response) = $this->getConsentsUsingGETWithHttpInfo($filter_application_user_id, $filter_user_uuid, $filter_institution, $filter_status, $from, $before, $limit, $offset);
        return $response;
    }

    /**
     * Operation getConsentsUsingGETWithHttpInfo
     *
     * Get consents sorted by creation date
     *
     * @param  string[] $filter_application_user_id Filter consents by your application user Id (applicationUserId) (optional)
     * @param  string[] $filter_user_uuid Filter consents by Yapily user Id (userUuid) (optional)
     * @param  string[] $filter_institution Use this parameter to filter consent by institution, using the Yapily institution Id (optional)
     * @param  string[] $filter_status Use this parameter to filter consent by status (optional)
     * @param  string $from Use this parameter to filter consents created after the date specified (optional)
     * @param  string $before Use this parameter to filter consents created before the date specified (optional)
     * @param  int $limit Use this parameter to limit consent results, max limit is 20 (optional)
     * @param  int $offset Use this parameter to specify the offset of the results (optional, default to 0)
     *
     * @throws \Yapily\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Yapily\Model\ApiListResponseOfConsent, HTTP status code, HTTP response headers (array of strings)
     */
    public function getConsentsUsingGETWithHttpInfo($filter_application_user_id = null, $filter_user_uuid = null, $filter_institution = null, $filter_status = null, $from = null, $before = null, $limit = null, $offset = '0')
    {
        $returnType = '\Yapily\Model\ApiListResponseOfConsent';
        $request = $this->getConsentsUsingGETRequest($filter_application_user_id, $filter_user_uuid, $filter_institution, $filter_status, $from, $before, $limit, $offset);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Yapily\Model\ApiListResponseOfConsent',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getConsentsUsingGETAsync
     *
     * Get consents sorted by creation date
     *
     * @param  string[] $filter_application_user_id Filter consents by your application user Id (applicationUserId) (optional)
     * @param  string[] $filter_user_uuid Filter consents by Yapily user Id (userUuid) (optional)
     * @param  string[] $filter_institution Use this parameter to filter consent by institution, using the Yapily institution Id (optional)
     * @param  string[] $filter_status Use this parameter to filter consent by status (optional)
     * @param  string $from Use this parameter to filter consents created after the date specified (optional)
     * @param  string $before Use this parameter to filter consents created before the date specified (optional)
     * @param  int $limit Use this parameter to limit consent results, max limit is 20 (optional)
     * @param  int $offset Use this parameter to specify the offset of the results (optional, default to 0)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConsentsUsingGETAsync($filter_application_user_id = null, $filter_user_uuid = null, $filter_institution = null, $filter_status = null, $from = null, $before = null, $limit = null, $offset = '0')
    {
        return $this->getConsentsUsingGETAsyncWithHttpInfo($filter_application_user_id, $filter_user_uuid, $filter_institution, $filter_status, $from, $before, $limit, $offset)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getConsentsUsingGETAsyncWithHttpInfo
     *
     * Get consents sorted by creation date
     *
     * @param  string[] $filter_application_user_id Filter consents by your application user Id (applicationUserId) (optional)
     * @param  string[] $filter_user_uuid Filter consents by Yapily user Id (userUuid) (optional)
     * @param  string[] $filter_institution Use this parameter to filter consent by institution, using the Yapily institution Id (optional)
     * @param  string[] $filter_status Use this parameter to filter consent by status (optional)
     * @param  string $from Use this parameter to filter consents created after the date specified (optional)
     * @param  string $before Use this parameter to filter consents created before the date specified (optional)
     * @param  int $limit Use this parameter to limit consent results, max limit is 20 (optional)
     * @param  int $offset Use this parameter to specify the offset of the results (optional, default to 0)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConsentsUsingGETAsyncWithHttpInfo($filter_application_user_id = null, $filter_user_uuid = null, $filter_institution = null, $filter_status = null, $from = null, $before = null, $limit = null, $offset = '0')
    {
        $returnType = '\Yapily\Model\ApiListResponseOfConsent';
        $request = $this->getConsentsUsingGETRequest($filter_application_user_id, $filter_user_uuid, $filter_institution, $filter_status, $from, $before, $limit, $offset);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getConsentsUsingGET'
     *
     * @param  string[] $filter_application_user_id Filter consents by your application user Id (applicationUserId) (optional)
     * @param  string[] $filter_user_uuid Filter consents by Yapily user Id (userUuid) (optional)
     * @param  string[] $filter_institution Use this parameter to filter consent by institution, using the Yapily institution Id (optional)
     * @param  string[] $filter_status Use this parameter to filter consent by status (optional)
     * @param  string $from Use this parameter to filter consents created after the date specified (optional)
     * @param  string $before Use this parameter to filter consents created before the date specified (optional)
     * @param  int $limit Use this parameter to limit consent results, max limit is 20 (optional)
     * @param  int $offset Use this parameter to specify the offset of the results (optional, default to 0)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getConsentsUsingGETRequest($filter_application_user_id = null, $filter_user_uuid = null, $filter_institution = null, $filter_status = null, $from = null, $before = null, $limit = null, $offset = '0')
    {

        $resourcePath = '/consents';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if (is_array($filter_application_user_id)) {
            $queryParams['filter[applicationUserId]'] = $filter_application_user_id;
        } else
        if ($filter_application_user_id !== null) {
            $queryParams['filter[applicationUserId]'] = ObjectSerializer::toQueryValue($filter_application_user_id);
        }
        // query params
        if (is_array($filter_user_uuid)) {
            $queryParams['filter[userUuid]'] = $filter_user_uuid;
        } else
        if ($filter_user_uuid !== null) {
            $queryParams['filter[userUuid]'] = ObjectSerializer::toQueryValue($filter_user_uuid);
        }
        // query params
        if (is_array($filter_institution)) {
            $queryParams['filter[institution]'] = $filter_institution;
        } else
        if ($filter_institution !== null) {
            $queryParams['filter[institution]'] = ObjectSerializer::toQueryValue($filter_institution);
        }
        // query params
        if (is_array($filter_status)) {
            $queryParams['filter[status]'] = $filter_status;
        } else
        if ($filter_status !== null) {
            $queryParams['filter[status]'] = ObjectSerializer::toQueryValue($filter_status);
        }
        // query params
        if ($from !== null) {
            $queryParams['from'] = ObjectSerializer::toQueryValue($from);
        }
        // query params
        if ($before !== null) {
            $queryParams['before'] = ObjectSerializer::toQueryValue($before);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($offset !== null) {
            $queryParams['offset'] = ObjectSerializer::toQueryValue($offset);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json;charset=UTF-8']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json;charset=UTF-8'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getUserConsentsUsingGET
     *
     * Get latest user consents
     *
     * @param  string $user_uuid userUuid (required)
     * @param  string $filter_institution Use this parameter to filter consent by institution, using the Yapily institution Id. This replaces the deprecated &#x60;institutionId&#x60; query param. (optional)
     * @param  int $limit Use this parameter to limit consent results, max limit is 20 (optional)
     *
     * @throws \Yapily\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Yapily\Model\Consent[]
     */
    public function getUserConsentsUsingGET($user_uuid, $filter_institution = null, $limit = null)
    {
        list($response) = $this->getUserConsentsUsingGETWithHttpInfo($user_uuid, $filter_institution, $limit);
        return $response;
    }

    /**
     * Operation getUserConsentsUsingGETWithHttpInfo
     *
     * Get latest user consents
     *
     * @param  string $user_uuid userUuid (required)
     * @param  string $filter_institution Use this parameter to filter consent by institution, using the Yapily institution Id. This replaces the deprecated &#x60;institutionId&#x60; query param. (optional)
     * @param  int $limit Use this parameter to limit consent results, max limit is 20 (optional)
     *
     * @throws \Yapily\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Yapily\Model\Consent[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getUserConsentsUsingGETWithHttpInfo($user_uuid, $filter_institution = null, $limit = null)
    {
        $returnType = '\Yapily\Model\Consent[]';
        $request = $this->getUserConsentsUsingGETRequest($user_uuid, $filter_institution, $limit);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Yapily\Model\Consent[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getUserConsentsUsingGETAsync
     *
     * Get latest user consents
     *
     * @param  string $user_uuid userUuid (required)
     * @param  string $filter_institution Use this parameter to filter consent by institution, using the Yapily institution Id. This replaces the deprecated &#x60;institutionId&#x60; query param. (optional)
     * @param  int $limit Use this parameter to limit consent results, max limit is 20 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUserConsentsUsingGETAsync($user_uuid, $filter_institution = null, $limit = null)
    {
        return $this->getUserConsentsUsingGETAsyncWithHttpInfo($user_uuid, $filter_institution, $limit)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getUserConsentsUsingGETAsyncWithHttpInfo
     *
     * Get latest user consents
     *
     * @param  string $user_uuid userUuid (required)
     * @param  string $filter_institution Use this parameter to filter consent by institution, using the Yapily institution Id. This replaces the deprecated &#x60;institutionId&#x60; query param. (optional)
     * @param  int $limit Use this parameter to limit consent results, max limit is 20 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUserConsentsUsingGETAsyncWithHttpInfo($user_uuid, $filter_institution = null, $limit = null)
    {
        $returnType = '\Yapily\Model\Consent[]';
        $request = $this->getUserConsentsUsingGETRequest($user_uuid, $filter_institution, $limit);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getUserConsentsUsingGET'
     *
     * @param  string $user_uuid userUuid (required)
     * @param  string $filter_institution Use this parameter to filter consent by institution, using the Yapily institution Id. This replaces the deprecated &#x60;institutionId&#x60; query param. (optional)
     * @param  int $limit Use this parameter to limit consent results, max limit is 20 (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getUserConsentsUsingGETRequest($user_uuid, $filter_institution = null, $limit = null)
    {
        // verify the required parameter 'user_uuid' is set
        if ($user_uuid === null || (is_array($user_uuid) && count($user_uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $user_uuid when calling getUserConsentsUsingGET'
            );
        }

        $resourcePath = '/users/{userUuid}/consents';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($filter_institution !== null) {
            $queryParams['filter[institution]'] = ObjectSerializer::toQueryValue($filter_institution);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }

        // path params
        if ($user_uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'userUuid' . '}',
                ObjectSerializer::toPathValue($user_uuid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json;charset=UTF-8']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json;charset=UTF-8'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if ($this->config->getUsername() !== null || $this->config->getPassword() !== null) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
