<?php
/**
 * ATMMapServiceLinks
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yapily
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yapily API
 *
 * To access endpoints that require authentication, use your Application key and secret created in the Dashboard (https://dashboard.yapily.com)
 *
 * OpenAPI spec version: 0.0.85
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Yapily\Model;

use \ArrayAccess;
use \Yapily\ObjectSerializer;

/**
 * ATMMapServiceLinks Class Doc Comment
 *
 * @category Class
 * @description Links on popular map services pointing the ATM Location on the earth.
 * @package  Yapily
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ATMMapServiceLinks implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ATMMapServiceLinks';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'bing_maps_url' => 'string',
        'google_maps_url' => 'string',
        'here_maps_url' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'bing_maps_url' => null,
        'google_maps_url' => null,
        'here_maps_url' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bing_maps_url' => 'bingMapsUrl',
        'google_maps_url' => 'googleMapsUrl',
        'here_maps_url' => 'hereMapsUrl'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bing_maps_url' => 'setBingMapsUrl',
        'google_maps_url' => 'setGoogleMapsUrl',
        'here_maps_url' => 'setHereMapsUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bing_maps_url' => 'getBingMapsUrl',
        'google_maps_url' => 'getGoogleMapsUrl',
        'here_maps_url' => 'getHereMapsUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['bing_maps_url'] = isset($data['bing_maps_url']) ? $data['bing_maps_url'] : null;
        $this->container['google_maps_url'] = isset($data['google_maps_url']) ? $data['google_maps_url'] : null;
        $this->container['here_maps_url'] = isset($data['here_maps_url']) ? $data['here_maps_url'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets bing_maps_url
     *
     * @return string
     */
    public function getBingMapsUrl()
    {
        return $this->container['bing_maps_url'];
    }

    /**
     * Sets bing_maps_url
     *
     * @param string $bing_maps_url bing_maps_url
     *
     * @return $this
     */
    public function setBingMapsUrl($bing_maps_url)
    {
        $this->container['bing_maps_url'] = $bing_maps_url;

        return $this;
    }

    /**
     * Gets google_maps_url
     *
     * @return string
     */
    public function getGoogleMapsUrl()
    {
        return $this->container['google_maps_url'];
    }

    /**
     * Sets google_maps_url
     *
     * @param string $google_maps_url google_maps_url
     *
     * @return $this
     */
    public function setGoogleMapsUrl($google_maps_url)
    {
        $this->container['google_maps_url'] = $google_maps_url;

        return $this;
    }

    /**
     * Gets here_maps_url
     *
     * @return string
     */
    public function getHereMapsUrl()
    {
        return $this->container['here_maps_url'];
    }

    /**
     * Sets here_maps_url
     *
     * @param string $here_maps_url here_maps_url
     *
     * @return $this
     */
    public function setHereMapsUrl($here_maps_url)
    {
        $this->container['here_maps_url'] = $here_maps_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


