<?php
/**
 * CurrencyExchangeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yapily
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yapily API
 *
 * To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)
 *
 * OpenAPI spec version: 0.0.149
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Yapily;

/**
 * CurrencyExchangeTest Class Doc Comment
 *
 * @category    Class
 * @description CurrencyExchange
 * @package     Yapily
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CurrencyExchangeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CurrencyExchange"
     */
    public function testCurrencyExchange()
    {
    }

    /**
     * Test attribute "source_currency"
     */
    public function testPropertySourceCurrency()
    {
    }

    /**
     * Test attribute "target_currency"
     */
    public function testPropertyTargetCurrency()
    {
    }

    /**
     * Test attribute "unit_currency"
     */
    public function testPropertyUnitCurrency()
    {
    }

    /**
     * Test attribute "exchange_rate"
     */
    public function testPropertyExchangeRate()
    {
    }
}
