<?php
/**
 * EligibilityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yapily
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yapily API
 *
 * To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)
 *
 * OpenAPI spec version: 0.0.149
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Yapily;

/**
 * EligibilityTest Class Doc Comment
 *
 * @category    Class
 * @description Eligibility details for this product i.e. the criteria that an accountholder has to meet in order to be eligible for the PCA product.
 * @package     Yapily
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EligibilityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Eligibility"
     */
    public function testEligibility()
    {
    }

    /**
     * Test attribute "age_eligibility"
     */
    public function testPropertyAgeEligibility()
    {
    }

    /**
     * Test attribute "credit_check"
     */
    public function testPropertyCreditCheck()
    {
    }

    /**
     * Test attribute "id_verification_check"
     */
    public function testPropertyIdVerificationCheck()
    {
    }

    /**
     * Test attribute "other_eligibility"
     */
    public function testPropertyOtherEligibility()
    {
    }

    /**
     * Test attribute "residency_eligibility"
     */
    public function testPropertyResidencyEligibility()
    {
    }
}
