<?php
/**
 * OverdraftOverdraftFeeChargeDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yapily
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yapily API
 *
 * To access endpoints that require authentication, use your Application key and secret created in the Dashboard (https://dashboard.yapily.com)
 *
 * OpenAPI spec version: 0.0.85
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Yapily;

/**
 * OverdraftOverdraftFeeChargeDetailTest Class Doc Comment
 *
 * @category    Class
 * @description Details about the fees/charges
 * @package     Yapily
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OverdraftOverdraftFeeChargeDetailTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OverdraftOverdraftFeeChargeDetail"
     */
    public function testOverdraftOverdraftFeeChargeDetail()
    {
    }

    /**
     * Test attribute "application_frequency"
     */
    public function testPropertyApplicationFrequency()
    {
    }

    /**
     * Test attribute "calculation_frequency"
     */
    public function testPropertyCalculationFrequency()
    {
    }

    /**
     * Test attribute "fee_amount"
     */
    public function testPropertyFeeAmount()
    {
    }

    /**
     * Test attribute "fee_rate"
     */
    public function testPropertyFeeRate()
    {
    }

    /**
     * Test attribute "fee_rate_type"
     */
    public function testPropertyFeeRateType()
    {
    }

    /**
     * Test attribute "fee_type"
     */
    public function testPropertyFeeType()
    {
    }

    /**
     * Test attribute "incremental_borrowing_amount"
     */
    public function testPropertyIncrementalBorrowingAmount()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "other_application_frequency"
     */
    public function testPropertyOtherApplicationFrequency()
    {
    }

    /**
     * Test attribute "other_calculation_frequency"
     */
    public function testPropertyOtherCalculationFrequency()
    {
    }

    /**
     * Test attribute "other_fee_rate_type"
     */
    public function testPropertyOtherFeeRateType()
    {
    }

    /**
     * Test attribute "other_fee_type"
     */
    public function testPropertyOtherFeeType()
    {
    }

    /**
     * Test attribute "overdraft_control_indicator"
     */
    public function testPropertyOverdraftControlIndicator()
    {
    }

    /**
     * Test attribute "overdraft_fee_applicable_range"
     */
    public function testPropertyOverdraftFeeApplicableRange()
    {
    }
}
