<?php
/**
 * OverdraftOverdraftTierBandSetTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yapily
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yapily API
 *
 * To access endpoints that require authentication, use your Application key and secret created in the Dashboard (https://dashboard.yapily.com)
 *
 * OpenAPI spec version: 0.0.85
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Yapily;

/**
 * OverdraftOverdraftTierBandSetTest Class Doc Comment
 *
 * @category    Class
 * @description Tier band set details
 * @package     Yapily
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OverdraftOverdraftTierBandSetTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OverdraftOverdraftTierBandSet"
     */
    public function testOverdraftOverdraftTierBandSet()
    {
    }

    /**
     * Test attribute "authorised_indicator"
     */
    public function testPropertyAuthorisedIndicator()
    {
    }

    /**
     * Test attribute "buffer_amount"
     */
    public function testPropertyBufferAmount()
    {
    }

    /**
     * Test attribute "identification"
     */
    public function testPropertyIdentification()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "overdraft_fees_charges"
     */
    public function testPropertyOverdraftFeesCharges()
    {
    }

    /**
     * Test attribute "overdraft_tier_band"
     */
    public function testPropertyOverdraftTierBand()
    {
    }

    /**
     * Test attribute "overdraft_type"
     */
    public function testPropertyOverdraftType()
    {
    }

    /**
     * Test attribute "tier_band_method"
     */
    public function testPropertyTierBandMethod()
    {
    }
}
