<?php
/**
 * PaymentAuthorisationRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Yapily
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yapily API
 *
 * To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)
 *
 * OpenAPI spec version: 0.0.161
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Yapily;

/**
 * PaymentAuthorisationRequestTest Class Doc Comment
 *
 * @category    Class
 * @description PaymentAuthorisationRequest
 * @package     Yapily
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentAuthorisationRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PaymentAuthorisationRequest"
     */
    public function testPaymentAuthorisationRequest()
    {
    }

    /**
     * Test attribute "user_uuid"
     */
    public function testPropertyUserUuid()
    {
    }

    /**
     * Test attribute "application_user_id"
     */
    public function testPropertyApplicationUserId()
    {
    }

    /**
     * Test attribute "forward_parameters"
     */
    public function testPropertyForwardParameters()
    {
    }

    /**
     * Test attribute "institution_id"
     */
    public function testPropertyInstitutionId()
    {
    }

    /**
     * Test attribute "callback"
     */
    public function testPropertyCallback()
    {
    }

    /**
     * Test attribute "one_time_token"
     */
    public function testPropertyOneTimeToken()
    {
    }

    /**
     * Test attribute "payment_request"
     */
    public function testPropertyPaymentRequest()
    {
    }

    /**
     * Test attribute "total_max_amount"
     */
    public function testPropertyTotalMaxAmount()
    {
    }

    /**
     * Test attribute "total_max_amount_frequency"
     */
    public function testPropertyTotalMaxAmountFrequency()
    {
    }

    /**
     * Test attribute "max_amount_per_request"
     */
    public function testPropertyMaxAmountPerRequest()
    {
    }

    /**
     * Test attribute "starts_at"
     */
    public function testPropertyStartsAt()
    {
    }

    /**
     * Test attribute "expires_at"
     */
    public function testPropertyExpiresAt()
    {
    }

    /**
     * Test attribute "allow_overdraft"
     */
    public function testPropertyAllowOverdraft()
    {
    }
}
