<?php
/**
 * ApplicationUsersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Yapily
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yapily API
 *
 * To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)
 *
 * OpenAPI spec version: 0.0.161
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Yapily;

use \Yapily\Configuration;
use \Yapily\ApiException;
use \Yapily\ObjectSerializer;

/**
 * ApplicationUsersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Yapily
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ApplicationUsersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addUserUsingPOST
     *
     * Add an application user.
     *
     */
    public function testAddUserUsingPOST()
    {
    }

    /**
     * Test case for deleteUserUsingDELETE
     *
     * Delete an application user and sub-resources (including consent resources on institution APIs if they exist).
     *
     */
    public function testDeleteUserUsingDELETE()
    {
    }

    /**
     * Test case for getDeleteUsersJobUsingGET
     *
     * Get details of a user deletion job.
     *
     */
    public function testGetDeleteUsersJobUsingGET()
    {
    }

    /**
     * Test case for getDeleteUsersJobsUsingGET
     *
     * Get details of all user deletion jobs.
     *
     */
    public function testGetDeleteUsersJobsUsingGET()
    {
    }

    /**
     * Test case for getUserUsingGET
     *
     * Get an application user.
     *
     */
    public function testGetUserUsingGET()
    {
    }

    /**
     * Test case for getUsersUsingGET
     *
     * Get application users.
     *
     */
    public function testGetUsersUsingGET()
    {
    }

    /**
     * Test case for startDeleteUsersJobUsingPOST
     *
     * Start a job to delete application users by specifying their identifiers.
     *
     */
    public function testStartDeleteUsersJobUsingPOST()
    {
    }
}
