<?php
/**
 * ApplicationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Yapily
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Yapily API
 *
 * To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)
 *
 * OpenAPI spec version: 0.0.161
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Yapily;

use \Yapily\Configuration;
use \Yapily\ApiException;
use \Yapily\ObjectSerializer;

/**
 * ApplicationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Yapily
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ApplicationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getApplicationMeUsingGET
     *
     * Returns the details of the application that owns the request credentials.
     *
     */
    public function testGetApplicationMeUsingGET()
    {
    }

    /**
     * Test case for getJwksUsingGET
     *
     * JSON Web Key Set (JWKS) for authenticated application.
     *
     */
    public function testGetJwksUsingGET()
    {
    }

    /**
     * Test case for revokeTokensUsingPOST
     *
     * Revoke existing access tokens for application, which will also generate a new public key discoverable via /jwks.
     *
     */
    public function testRevokeTokensUsingPOST()
    {
    }
}
